#!/usr/bin/env python3
"""Pain To Pip Package — convert Reddit pain signals into pip-installable CLI tools.

Usage:
    python pipeline.py --source pain_signals.json     # build from pain cluster
    python pipeline.py --name my-tool --desc "..."     # quick scaffold
"""

import argparse
import json
import os
import re
import shutil
import sys
from pathlib import Path
from datetime import datetime


SETUP_PY_TEMPLATE = '''from setuptools import setup, find_packages

with open("README.md", "r") as f:
    long_description = f.read()

setup(
    name="{name}",
    version="0.1.0",
    author="minirr890112-byte",
    description="{description}",
    long_description=long_description,
    long_description_content_type="text/markdown",
    url="https://github.com/minirr890112-byte/{name}",
    packages=find_packages(),
    entry_points={{
        "console_scripts": [
            "{name}={name}.cli:main",
        ],
    }},
    python_requires=">=3.10",
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
    ],
)
'''

CLI_TEMPLATE = '''"""CLI entry point for {name}. Auto-generated by Pain To Pip Pipeline."""

import argparse
import sys


def main():
    parser = argparse.ArgumentParser(description="{description}")
{args_block}
    args = parser.parse_args()

    # TODO: Implement core logic
    print(f"🚀 {name} v0.1.0")
    print(f"   {description}")
    print(f"   Created from pain signals on {date}")
    print()
    print("⚙️  Core logic — implement in {name}/core.py")

    return 0


if __name__ == "__main__":
    sys.exit(main())
'''

README_TEMPLATE = '''# {title}

{warning}

> Built from real developer pain signals using [Pain To Pip Pipeline](https://github.com/minirr890112-byte/pain-to-pip-package).

## Pain Provenance

| Source | Signal | Replies |
|---|---|---|
{signals_table}

## Install

```bash
pip install git+https://github.com/minirr890112-byte/{name}.git
```

## Usage

```bash
{name} --help
```

## Why a Star? ⭐

Born from real pain. If this solves (or might solve) a problem for you, star it to help others find it → [GitHub](https://github.com/minirr890112-byte/{name})
'''


def slugify(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")


def scaffold(name: str, description: str, pain_signals: list[dict] | None = None,
             output_dir: str = ".") -> str:
    """Generate a pip-installable CLI tool skeleton from pain signals."""
    package_dir = Path(output_dir) / name
    package_dir.mkdir(parents=True, exist_ok=True)

    # Create package
    inner = package_dir / name
    inner.mkdir(exist_ok=True)

    # __init__.py
    (inner / "__init__.py").write_text(f'"""{{name}} — {{description}}"""\n\n__version__ = "0.1.0"\n')

    # core.py
    (inner / "core.py").write_text(f'"""Core module for {name}."""\n\n\ndef hello() -> str:\n    return "Hello from {name}!"\n')

    # cli.py with pain-based args
    args_block = ""
    if pain_signals:
        categories = set()
        for s in pain_signals:
            for c in s.get("categories", []):
                categories.add(c.lower())
        for cat in sorted(categories)[:5]:
            args_block += f'    parser.add_argument("--{slugify(cat)}", action="store_true", help="Fix {cat.upper()} issues")\n'
    else:
        args_block = '    parser.add_argument("--fix", action="store_true", help="Auto-fix mode")\n'

    cli_content = CLI_TEMPLATE.format(
        name=name, description=description,
        args_block=args_block,
        date=datetime.now().strftime("%Y-%m-%d")
    )
    (inner / "cli.py").write_text(cli_content)

    # setup.py
    (package_dir / "setup.py").write_text(SETUP_PY_TEMPLATE.format(name=name, description=description))

    # README.md
    title = name.replace("-", " ").title()
    warning = "⚠️ **WORK IN PROGRESS** — core logic under development. Feedback welcome!"
    signals_table = ""
    if pain_signals:
        for s in pain_signals[:5]:
            signals_table += f"| r/{s.get('subreddit', '?')} | {s.get('title', '?')[:60]} | {s.get('comments', '?')} |\n"
    else:
        signals_table = "| N/A | Auto-generated scaffold | — |\n"

    readme = README_TEMPLATE.format(
        title=title, warning=warning, signals_table=signals_table, name=name
    )
    (package_dir / "README.md").write_text(readme)

    return str(package_dir)


def load_signals(path: str) -> list[dict]:
    with open(path) as f:
        data = json.load(f)
    if isinstance(data, dict):
        return data.get("pain_signals", [])
    return data


def analyze_signals(signals: list[dict]) -> dict:
    """Analyze pain signal cluster to determine tool name and description."""
    if not signals:
        return {}

    # Most common subreddit
    subs = [s.get("subreddit", "") for s in signals]
    top_sub = max(set(subs), key=subs.count) if subs else "unknown"

    # Most common categories
    all_cats = []
    for s in signals:
        all_cats.extend(s.get("categories", []))
    cat_counts = {}
    for c in all_cats:
        cat_counts[c] = cat_counts.get(c, 0) + 1
    top_cats = sorted(cat_counts, key=cat_counts.get, reverse=True)[:3]

    # Generate name
    name_words = [top_sub]
    name_words.extend(top_cats[:2])
    name = slugify("-".join(name_words))[:40]

    desc = f"Fix {', '.join(top_cats)} issues detected across {len(signals)} pain signals from r/{top_sub}"
    return {"name": name, "description": desc}


def main():
    parser = argparse.ArgumentParser(description="Pain To Pip Package Pipeline")
    parser.add_argument("--source", help="JSON file with pain signals (from reddit-pain-workflow)")
    parser.add_argument("--name", help="Tool name override")
    parser.add_argument("--desc", help="Tool description override")
    parser.add_argument("--output", default=".", help="Output directory")
    args = parser.parse_args()

    if args.source:
        signals = load_signals(args.source)
        print(f"📊 Loaded {len(signals)} pain signals")

        if signals:
            analysis = analyze_signals(signals)
            name = args.name or analysis.get("name", "unnamed-tool")
            desc = args.desc or analysis.get("description", "Auto-generated tool")
        else:
            print("⚠️  No pain signals found in source file.")
            sys.exit(1)
    elif args.name:
        name = args.name
        desc = args.desc or "CLI tool"
    else:
        name = "my-tool"
        desc = "Auto-generated CLI tool"

    path = scaffold(name, desc, signals if 'signals' in dir() else None, args.output)
    print(f"✅ Tool scaffolded: {path}")
    print(f"   cd {path} && pip install -e .")
    print(f"   {name} --help")


if __name__ == "__main__":
    main()
